credentials:
  usernames:
    admin:
      email: roopathupakula01@gmail.com
      name: Roopa
      password: '$2a$12$PpiuXlOVyrfaCKIOFOWW1etMSVMnypGZ5shFGav4MQWpjLF50zYo.'

cookie:
  name: streamlit_auth
  key: some_secret_key_please_change_me # I recommend changing this to a random string
  expiry_days: 7
