credentials:
  usernames:
    admin:
      email: roopathupakula01@gmail.com
      name: Roopa
      password: '$2a$12$PpiuXlOVyrfaCKIOFOWW1etMSVMnypGZ5shFGav4MQWpjLF50zYo.'  # hashed password for: admin123

cookie:
  name: streamlit_auth
  key: some_secret_key
  expiry_days: 7

preauthorized:
  emails:
    - admin@example.com
